name: Compilation et déploiement

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Vérification du code
        uses: actions/checkout@v2

      - name: Installation des dépendances
        run: npm install

      - name: Compilation du code
        run: npm run build

      - name: Connexion au serveur FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /sirene/
          local-dir: ./dist/
